"""empty message

Revision ID: 8479638a8b79
Revises: dcbfb5f9c840
Create Date: 2020-05-13 23:20:52.004301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8479638a8b79'
down_revision = 'dcbfb5f9c840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('test', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
